# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 Wang Nan <pi3orama@163.com>

# Top makefile of kbuild standalone. This is also a sample makefile
# to show how to use kbuild standalone.
#
# `KBUILD_STANDALONE_SRCDIRS:` source directories of this project.
# `KBUILD_STANDALONE_TARGETS:` targets to build using kbuild standalone.
# `<target>_GOAL:`             make goals list passed to `<target>/Makefile`.
# `<target>_CONF:`             config of a target, like `need-builtin=1`.

KBUILD_STANDALONE_TARGETS := fixdep kconfig unifdef
KBUILD_STANDALONE_SRCDIRS := $(KBUILD_STANDALONE_TARGETS)

kconfig_GOAL := kconfig/mconf kconfig/conf

kbuild_standalone_path := $(realpath $(dir $(lastword $(MAKEFILE_LIST))))/kbuild
makefile_include := $(kbuild_standalone_path)/Makefile.include

# include Makefile.include to invoke kbuild standalone.
include $(makefile_include)
